[package]
name = "rt-one"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bevy_color = "0.14.2"
bevy_math = "0.14.1"
clap = { version = "4.5.13", features = ["derive"] }
rand = "0.8.5"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
